spring.application.name=JobReferral

# PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-round-field-apkf0bv7.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IQ5rMtmS4DNV

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=jobReferralSecretKeyjobReferralSecretKey

# Server
server.port=8080